language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - pip install --quiet git+https://github.com/myint/cram
    - python setup.py --quiet install

script:
    - cram --indent=4 test.cram
    - python-modernize --future-unicode libmodernize
