#!/usr/bin/env python

import signal
import sys

from libmodernize.main import main


if __name__ == '__main__':
    # Exit on broken pipe.
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)

    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(2)
